### ISSUE TITLE
Non-Player heads breaking MPETs

### ISSUE THREAD

**Issue by Prenumbra** [miniaturepets/miniaturepets#117]
*Short description:* 
Using any Data tag other than 3 (to create something other than a player head) on a PLAYER_HEAD will cause the mpet to not move or form correctly.

*Long description*
Attempting to create an MPET that has a head, other than a player's, causes the MPET to break. Other parts of the MPET generate incorrectly, or not at all. The anchor also generates as visible regardless of what the config for it says. The entities will no longer be registered as an MPET and will not move with the anchor or run through its animation frames. The entities created cannot be removed through commands (that the plugin has).

Console will begin to spam the following as soon as the MPET is summoned:

[11:27:19 WARN]: [MiniaturePets] Task #10 for MiniaturePets v2.3.1 generated an exception
java.lang.NullPointerException: null
        at com.kirelcodes.miniaturepets.mob.Mob.isAnimationRunning(Mob.java:673) ~[?:?]
        at com.kirelcodes.miniaturepets.listener.CoreListener$1.run(CoreListener.java:79) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-171]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-171]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1147) ~[patched_1.14.4.jar:git-Paper-171]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-171]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[patched_1.14.4.jar:git-Paper-171]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-171]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

*Actions to repeat / ways of reaching the bug:* 
The bug can be easily repeated by making an MPET with this in the items.yml (or any other Data tag other than 3):
   Material: SKULL_ITEM
   Data: 2

*Miniature Pets Dump Link:*
https://i.imgur.com/dOz2fGJ.png

**Comment by Omerrg** [comment]
Looking into it, Already found something that might be a solution, but will update you as soon as we have it working and running :)
