### ISSUE TITLE
i can't type /mpet help 2

### ISSUE THREAD

**Issue by kamaewpoong** [miniaturepets/miniaturepets#120]
i can't type /mpet help 2
>mpet help 2
[15:01:42] [Server thread/WARN]: Unexpected exception while parsing console command "mpet help 2"
org.bukkit.command.CommandException: Unhandled exception executing 'mpet help 2' in com.kirelcodes.miniaturepets.commands.MajorCommand(mpet)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:695) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:433) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:397) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:971) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:816) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang3/math/NumberUtils
        at com.kirelcodes.miniaturepets.commands.CommandLoader$2.executeCommand(CommandLoader.java:233) ~[MiniaturePets.jar:?]
        at com.kirelcodes.miniaturepets.commands.CommandManager.executeCommand(CommandManager.java:115) ~[MiniaturePets.jar:?]
        at com.kirelcodes.miniaturepets.commands.MajorCommand.execute(MajorCommand.java:233) ~[MiniaturePets.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]

*Miniature Pets Dump Link:*

**Comment by NacOJerk** [comment]
Should be fixed in the newest release
