### ISSUE TITLE
MiniaturePets does not work on OpenJ9

### ISSUE THREAD

**Issue by Govindass** [MiniaturePets/MiniaturePets#168]
*Short Description:* 
MiniaturePets does not work on OpenJ9
*Long Description:* 
MiniaturePets does not work on OpenJ9, throwing this error:
[15:34:26] [Server thread/INFO]: Loading reflections....
[15:34:26] [Server thread/WARN]: java.lang.IllegalAccessException: illegal setter on final field
[15:34:26] [Server thread/WARN]: 	at java.base/java.lang.invoke.MethodHandles$Lookup.unreflectSetter(MethodHandles.java:1299)
[15:34:26] [Server thread/WARN]: 	at com.kirelcodes.miniaturepets.annotation.reflection.FieldAccessor.unreflect(FieldAccessor.java:38)
[15:34:26] [Server thread/WARN]: 	at com.kirelcodes.miniaturepets.annotation.reflection.FieldAccessor.unreflect(FieldAccessor.java:22)
[15:34:26] [Server thread/WARN]: 	at com.kirelcodes.miniaturepets.annotation.reflection.ReflectionAnnotationHandler.handleReflectedField(ReflectionAnnotationHandler.java:174)
[15:34:26] [Server thread/WARN]: 	at com.kirelcodes.miniaturepets.annotation.reflection.ReflectionAnnotationHandler.handleClass(ReflectionAnnotationHandler.java:47)
[15:34:26] [Server thread/WARN]: 	at com.kirelcodes.miniaturepets.reflections.GlobalReflectionResolver.resolve(GlobalReflectionResolver.java:140)
[15:34:26] [Server thread/WARN]: 	at com.kirelcodes.miniaturepets.MiniaturePets.setupReflections(MiniaturePets.java:235)
[15:34:26] [Server thread/WARN]: 	at com.kirelcodes.miniaturepets.MiniaturePets.onEnable(MiniaturePets.java:100)
[15:34:26] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[15:34:26] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[15:34:26] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[15:34:26] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[15:34:26] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[15:34:26] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[15:34:26] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[15:34:26] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[15:34:26] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[15:34:26] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[15:34:26] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[15:34:26] [Server thread/INFO]: Done loading
[15:34:26] [Server thread/INFO]: [MiniaturePets] Starting to calculate Radians!

**Comment by danielnaaman** [comment]
By OpenJ9, you refer to OpenJDK 9?

**Comment by Govindass** [comment]
> By OpenJ9, you refer to OpenJDK 9?

I refer to java 11 openj9

**Comment by Govindass** [comment]
to be more precise:
root@vmi356843:~# java -version                                                 openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Linux amd64-64-Bit Compressed References 20200122_441 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - da35e0c380 based on jdk-11.0.6+10)
root@vmi356843:~#

**Comment by liorsl** [comment]
Hello,
This issue should be fixed on the next version.

**Comment by Govindass** [comment]
> 
> 
> Hello,
> This issue should be fixed on the next version.

when will it release?

**Comment by danielnaaman** [comment]
Probably upcoming days, worst case scenario next week.

**Comment by Ollieed** [comment]
Any update on this update? Still waiting on a fix.

**Comment by danielnaaman** [comment]
Will release probably today.
