### ISSUE TITLE
MythicMobs add-on Miniaturepets Still not working?

### ISSUE THREAD

**Issue by MrBearLoL** [miniaturepets/miniaturepets#95]
I have this mob in mythicmobs, and its not working...:

AngryPug:
  Type: MPET
  MPet:
    Type: pug
    Anchor: SPIDER
    ShowName: true
  Display: 'Angry Pug'

Here is the error i get to console:

[19:38:58 WARN]: java.lang.NullPointerException
[19:38:58 WARN]:        at com.kirelcodes.miniaturepets.mob.Mob.hasCustomName(Mob.java:218)
[19:38:58 WARN]:        at com.kirelcodes.miniaturepets.mob.Mob.setVisible(Mob.java:403)
[19:38:58 WARN]:        at io.lumine.xikage.mythicmobs.compatibility.MPetCompat$MiniaturePetType.spawn(MPetCompat.java:69)
[19:38:58 WARN]:        at io.lumine.xikage.mythicmobs.mobs.MythicMob.spawn(MythicMob.java:661)
[19:38:58 WARN]:        at io.lumine.xikage.mythicmobs.mobs.MobManager.spawnMob(MobManager.java:436)
[19:38:58 WARN]:        at io.lumine.xikage.mythicmobs.mobs.MobManager.spawnMob(MobManager.java:425)
[19:38:58 WARN]:        at io.lumine.xikage.mythicmobs.commands.mobs.SpawnCommand.onCommand(SpawnCommand.java:129)
[19:38:58 WARN]:        at io.lumine.utils.commands.Command.onCommand(Command.java:69)
[19:38:58 WARN]:        at io.lumine.utils.commands.Command.onCommand(Command.java:60)
[19:38:58 WARN]:        at io.lumine.utils.commands.Command.onCommand(Command.java:60)
[19:38:58 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[19:38:58 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[19:38:58 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[19:38:58 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1478)
[19:38:58 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1283)
[19:38:58 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[19:38:58 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[19:38:58 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[19:38:58 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[19:38:58 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[19:38:58 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[19:38:58 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
[19:38:58 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[19:38:58 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[19:38:58 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[19:38:58 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by amokinio** [comment]
Hello, does the plugin function well without MythicMobs?

**Comment by MrBearLoL** [comment]
> Hello, does the plugin function well without MythicMobs?
Yes, it works well.

**Comment by MrBearLoL** [comment]
This error is from Mythicmobs

**Comment by amokinio** [comment]
Then we can't provide assistance for an issue with MythicMobs. You should contact their support team.
