### ISSUE TITLE
Unable to measure distance between worlds

### ISSUE THREAD

**Issue by LittleWorms** [miniaturepets/miniaturepets#97]
When I teleport to another world with pets. The server get error like this. help me
 
[18:43:54] [Server thread/WARN]: Ignoring unknown attribute 'miniaturepets.id'
[18:43:54] [Server thread/WARN]: Ignoring unknown attribute 'miniaturepets.id'
[18:43:54] [Server thread/WARN]: Ignoring unknown attribute 'miniaturepets.id'
[18:43:54] [Server thread/WARN]: [MiniaturePets] Task #75 for MiniaturePets v2.1.8 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between world and Dungeon
	at org.bukkit.Location.distanceSquared(Location.java:460) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at com.kirelcodes.miniaturepets.listener.CoreListener$1.run(CoreListener.java:80) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[18:43:54] [Server thread/WARN]: [MiniaturePets] Task #75 for MiniaturePets v2.1.8 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between world and Dungeon
	at org.bukkit.Location.distanceSquared(Location.java:460) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at com.kirelcodes.miniaturepets.listener.CoreListener$1.run(CoreListener.java:80) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at java.lang.Thread.run(Unknown Source)

**Comment by NacOJerk** [comment]
Can you provide a mpet dump ?

**Comment by NacOJerk** [comment]
Not active any more, seems to be solved
